packages:
  - 'packages/*'
  - 'packages/plugins/*'

allowBuilds:
  '@biomejs/biome': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  keytar: true
  sharp: true

catalogs:

  build:
    '@tailwindcss/vite': ^4.1.18
    '@vitejs/plugin-react': ^6.0.1
    tailwindcss: ^4.1.18

  git-hooks:
    '@commitlint/cli': ^20.5.3
    '@commitlint/config-conventional': ^21.0.1
    husky: ^9.1.7
    lint-staged: ^17.0.5

  libs:
    es-toolkit: ^1.47.0
    lucide-react: ^1.14.0
    octokit: ^5.0.5

  lint:
    '@biomejs/biome': ^2.4.15

  react:
    react: ^19.2.0
    react-dom: ^19.2.0

  tanstack:
    '@tanstack/devtools-vite': ^0.6.0
    '@tanstack/react-devtools': ^0.10.2
    '@tanstack/react-query': ^5.100.10
    '@tanstack/react-router': ^1.169.1
    '@tanstack/react-router-devtools': ^1.166.13
    '@tanstack/react-router-ssr-query': ^1.166.12
    '@tanstack/react-start': ^1.167.62
    '@tanstack/router-plugin': ^1.167.32

  test:
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.2
    '@testing-library/user-event': ^14.6.1
    '@vitest/coverage-v8': ^4.1.5
    '@vitest/ui': ^4.1.5
    jsdom: ^29.1.1
    vitest: ^4.1.5

  types:
    '@types/node': ^25.6.0
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    typescript: ^6.0.2
