export {
  getTaxonomySummary,
  renameTaxonomy,
  deleteTaxonomy,
  mergeTaxonomy,
  summarizeTaxonomies,
  renamePostTaxonomy,
  deletePostTaxonomy,
  mergePostTaxonomy,
  type TaxonomyItem,
  type TaxonomySummary,
  type TaxonomyType,
  type TaxonomyRepository,
  type TaxonomyMutation,
  type TaxonomyDeleteInput,
  type TaxonomyMergeInput,
} from "@hexo-cms/core";
