/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsNewRouteImport } from './routes/posts.new'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as PagesNewRouteImport } from './routes/pages.new'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ApiDeployRouteImport } from './routes/api/deploy'
import { Route as ApiGithubThemesRouteImport } from './routes/api/github/themes'
import { Route as ApiGithubTagsRouteImport } from './routes/api/github/tags'
import { Route as ApiGithubStatsRouteImport } from './routes/api/github/stats'
import { Route as ApiGithubPostsRouteImport } from './routes/api/github/posts'
import { Route as ApiGithubPagesRouteImport } from './routes/api/github/pages'
import { Route as ApiGithubMediaRouteImport } from './routes/api/github/media'
import { Route as ApiGithubConfigRouteImport } from './routes/api/github/config'
import { Route as ApiAuthTokenRouteImport } from './routes/api/auth/token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PostsRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)
const PagesNewRoute = PagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PagesRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const ApiDeployRoute = ApiDeployRouteImport.update({
  id: '/api/deploy',
  path: '/api/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubThemesRoute = ApiGithubThemesRouteImport.update({
  id: '/api/github/themes',
  path: '/api/github/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubTagsRoute = ApiGithubTagsRouteImport.update({
  id: '/api/github/tags',
  path: '/api/github/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStatsRoute = ApiGithubStatsRouteImport.update({
  id: '/api/github/stats',
  path: '/api/github/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPostsRoute = ApiGithubPostsRouteImport.update({
  id: '/api/github/posts',
  path: '/api/github/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPagesRoute = ApiGithubPagesRouteImport.update({
  id: '/api/github/pages',
  path: '/api/github/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubMediaRoute = ApiGithubMediaRouteImport.update({
  id: '/api/github/media',
  path: '/api/github/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConfigRoute = ApiGithubConfigRouteImport.update({
  id: '/api/github/config',
  path: '/api/github/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokenRoute = ApiAuthTokenRouteImport.update({
  id: '/api/auth/token',
  path: '/api/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/deploy': typeof DeployRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/pages': typeof PagesRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/themes': typeof ThemesRoute
  '/api/deploy': typeof ApiDeployRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/new': typeof PagesNewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/github/config': typeof ApiGithubConfigRoute
  '/api/github/media': typeof ApiGithubMediaRoute
  '/api/github/pages': typeof ApiGithubPagesRoute
  '/api/github/posts': typeof ApiGithubPostsRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
  '/api/github/tags': typeof ApiGithubTagsRoute
  '/api/github/themes': typeof ApiGithubThemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/deploy': typeof DeployRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/pages': typeof PagesRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/themes': typeof ThemesRoute
  '/api/deploy': typeof ApiDeployRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/new': typeof PagesNewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/github/config': typeof ApiGithubConfigRoute
  '/api/github/media': typeof ApiGithubMediaRoute
  '/api/github/pages': typeof ApiGithubPagesRoute
  '/api/github/posts': typeof ApiGithubPostsRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
  '/api/github/tags': typeof ApiGithubTagsRoute
  '/api/github/themes': typeof ApiGithubThemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/deploy': typeof DeployRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/pages': typeof PagesRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/themes': typeof ThemesRoute
  '/api/deploy': typeof ApiDeployRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/new': typeof PagesNewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/github/config': typeof ApiGithubConfigRoute
  '/api/github/media': typeof ApiGithubMediaRoute
  '/api/github/pages': typeof ApiGithubPagesRoute
  '/api/github/posts': typeof ApiGithubPostsRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
  '/api/github/tags': typeof ApiGithubTagsRoute
  '/api/github/themes': typeof ApiGithubThemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comments'
    | '/deploy'
    | '/login'
    | '/media'
    | '/onboarding'
    | '/pages'
    | '/posts'
    | '/settings'
    | '/tags'
    | '/themes'
    | '/api/deploy'
    | '/pages/$slug'
    | '/pages/new'
    | '/posts/$slug'
    | '/posts/new'
    | '/api/auth/$'
    | '/api/auth/token'
    | '/api/github/config'
    | '/api/github/media'
    | '/api/github/pages'
    | '/api/github/posts'
    | '/api/github/stats'
    | '/api/github/tags'
    | '/api/github/themes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comments'
    | '/deploy'
    | '/login'
    | '/media'
    | '/onboarding'
    | '/pages'
    | '/posts'
    | '/settings'
    | '/tags'
    | '/themes'
    | '/api/deploy'
    | '/pages/$slug'
    | '/pages/new'
    | '/posts/$slug'
    | '/posts/new'
    | '/api/auth/$'
    | '/api/auth/token'
    | '/api/github/config'
    | '/api/github/media'
    | '/api/github/pages'
    | '/api/github/posts'
    | '/api/github/stats'
    | '/api/github/tags'
    | '/api/github/themes'
  id:
    | '__root__'
    | '/'
    | '/comments'
    | '/deploy'
    | '/login'
    | '/media'
    | '/onboarding'
    | '/pages'
    | '/posts'
    | '/settings'
    | '/tags'
    | '/themes'
    | '/api/deploy'
    | '/pages/$slug'
    | '/pages/new'
    | '/posts/$slug'
    | '/posts/new'
    | '/api/auth/$'
    | '/api/auth/token'
    | '/api/github/config'
    | '/api/github/media'
    | '/api/github/pages'
    | '/api/github/posts'
    | '/api/github/stats'
    | '/api/github/tags'
    | '/api/github/themes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentsRoute: typeof CommentsRoute
  DeployRoute: typeof DeployRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  OnboardingRoute: typeof OnboardingRoute
  PagesRoute: typeof PagesRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TagsRoute: typeof TagsRoute
  ThemesRoute: typeof ThemesRoute
  ApiDeployRoute: typeof ApiDeployRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthTokenRoute: typeof ApiAuthTokenRoute
  ApiGithubConfigRoute: typeof ApiGithubConfigRoute
  ApiGithubMediaRoute: typeof ApiGithubMediaRoute
  ApiGithubPagesRoute: typeof ApiGithubPagesRoute
  ApiGithubPostsRoute: typeof ApiGithubPostsRoute
  ApiGithubStatsRoute: typeof ApiGithubStatsRoute
  ApiGithubTagsRoute: typeof ApiGithubTagsRoute
  ApiGithubThemesRoute: typeof ApiGithubThemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
    '/pages/new': {
      id: '/pages/new'
      path: '/new'
      fullPath: '/pages/new'
      preLoaderRoute: typeof PagesNewRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/api/deploy': {
      id: '/api/deploy'
      path: '/api/deploy'
      fullPath: '/api/deploy'
      preLoaderRoute: typeof ApiDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/themes': {
      id: '/api/github/themes'
      path: '/api/github/themes'
      fullPath: '/api/github/themes'
      preLoaderRoute: typeof ApiGithubThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/tags': {
      id: '/api/github/tags'
      path: '/api/github/tags'
      fullPath: '/api/github/tags'
      preLoaderRoute: typeof ApiGithubTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/stats': {
      id: '/api/github/stats'
      path: '/api/github/stats'
      fullPath: '/api/github/stats'
      preLoaderRoute: typeof ApiGithubStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/posts': {
      id: '/api/github/posts'
      path: '/api/github/posts'
      fullPath: '/api/github/posts'
      preLoaderRoute: typeof ApiGithubPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/pages': {
      id: '/api/github/pages'
      path: '/api/github/pages'
      fullPath: '/api/github/pages'
      preLoaderRoute: typeof ApiGithubPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/media': {
      id: '/api/github/media'
      path: '/api/github/media'
      fullPath: '/api/github/media'
      preLoaderRoute: typeof ApiGithubMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/config': {
      id: '/api/github/config'
      path: '/api/github/config'
      fullPath: '/api/github/config'
      preLoaderRoute: typeof ApiGithubConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/token': {
      id: '/api/auth/token'
      path: '/api/auth/token'
      fullPath: '/api/auth/token'
      preLoaderRoute: typeof ApiAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PagesRouteChildren {
  PagesSlugRoute: typeof PagesSlugRoute
  PagesNewRoute: typeof PagesNewRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesSlugRoute: PagesSlugRoute,
  PagesNewRoute: PagesNewRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
  PostsNewRoute: typeof PostsNewRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
  PostsNewRoute: PostsNewRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentsRoute: CommentsRoute,
  DeployRoute: DeployRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  OnboardingRoute: OnboardingRoute,
  PagesRoute: PagesRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TagsRoute: TagsRoute,
  ThemesRoute: ThemesRoute,
  ApiDeployRoute: ApiDeployRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthTokenRoute: ApiAuthTokenRoute,
  ApiGithubConfigRoute: ApiGithubConfigRoute,
  ApiGithubMediaRoute: ApiGithubMediaRoute,
  ApiGithubPagesRoute: ApiGithubPagesRoute,
  ApiGithubPostsRoute: ApiGithubPostsRoute,
  ApiGithubStatsRoute: ApiGithubStatsRoute,
  ApiGithubTagsRoute: ApiGithubTagsRoute,
  ApiGithubThemesRoute: ApiGithubThemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
