import type { PluginManifest } from "@hexo-cms/core";

export const COMMENTS_OVERVIEW_PLUGIN_ID = "hexo-cms-comments-overview";

export const commentsOverviewManifest: PluginManifest = {
  id: COMMENTS_OVERVIEW_PLUGIN_ID,
  name: "Comments Overview",
  version: "0.1.0",
  description: "Manage Giscus comments backed by GitHub Discussions.",
  origin: "official",
  runtime: "hosted",
  engine: { hexoCms: ">=0.1.0" },
  activation: ["onDashboard"],
  permissions: ["ui.contribute", "pluginConfig.write", "command.register", "network.fetch"],
  network: { allowedHosts: ["api.github.com"] },
  contributes: {
    dashboardWidgets: [
      {
        id: "comments.overview",
        title: "Comments Overview",
        renderer: "comments.overview",
        size: "medium",
        order: 90,
      },
    ],
    settingsPanels: [
      {
        id: "comments.giscus",
        title: "Giscus Comments",
        schema: "comments.giscus",
      },
    ],
    settingsSchemas: {
      "comments.giscus": {
        id: "comments.giscus",
        fields: [
          { key: "giscusRepo", label: "GitHub repository", type: "string", defaultValue: "", required: true, placeholder: "owner/repo" },
          { key: "giscusRepoId", label: "Repository ID", type: "string", defaultValue: "", required: true, placeholder: "R_kgDO..." },
          { key: "giscusCategoryId", label: "Discussion Category ID", type: "string", defaultValue: "", required: true, placeholder: "DIC_kw..." },
          { key: "giscusCategory", label: "Discussion category", type: "string", defaultValue: "General", required: true },
        ],
      },
    },
    sidebarItems: [
      {
        id: "comments.entry",
        title: "评论管理",
        target: "/comments",
      },
    ],
    commands: [
      {
        id: "comments.openModeration",
        title: "打开评论管理",
      },
    ],
    translations: {
      zh: {
        "comments.widget.pending": "待审核",
        "comments.widget.approved": "已通过",
        "comments.widget.spam": "垃圾",
        "comments.widget.manageComments": "评论管理",
        "comments.widget.totalComments": "共 {{count}} 条示例评论",
        "comments.widget.openModeration": "打开评论管理",
        "comments.state.locked": "已锁定",
        "comments.state.answered": "已解决",
        "comments.filter.all": "全部",
        "comments.filter.open": "开放",
        "comments.filter.locked": "已锁定",
        "comments.filter.answered": "已解决",
        "comments.time.justNow": "刚刚",
        "comments.time.minutesAgo": "{{count}} 分钟前",
        "comments.time.hoursAgo": "{{count}} 小时前",
        "comments.time.daysAgo": "{{count}} 天前",
        "comments.page.notEnabled": "评论插件未启用",
        "comments.page.notEnabledDesc": "评论管理功能由 Comments Overview 插件提供，请在插件设置中启用。",
        "comments.page.enablePlugin": "启用评论插件",
        "comments.page.notConfigured": "尚未配置评论系统",
        "comments.page.notConfiguredDesc": "请在插件设置中配置 Giscus 参数（仓库、Repository ID、Category ID）后开始使用。",
        "comments.page.configureComments": "配置评论系统",
        "comments.page.title": "评论管理",
        "comments.page.totalDiscussions": "共 {{count}} 个 Discussion",
        "comments.page.refresh": "刷新",
        "comments.page.searchPlaceholder": "搜索讨论...",
        "comments.page.loading": "加载中...",
        "comments.page.loadFailed": "加载失败",
        "comments.page.loadingComments": "加载评论中...",
        "comments.page.noComments": "暂无评论",
        "comments.page.noMatch": "没有匹配的讨论",
        "comments.comment.hidden": "已隐藏",
        "comments.comment.unhide": "取消隐藏",
        "comments.comment.hide": "隐藏",
      },
      en: {
        "comments.widget.pending": "Pending",
        "comments.widget.approved": "Approved",
        "comments.widget.spam": "Spam",
        "comments.widget.manageComments": "Comment Management",
        "comments.widget.totalComments": "{{count}} sample comments total",
        "comments.widget.openModeration": "Open Comment Management",
        "comments.state.locked": "Locked",
        "comments.state.answered": "Resolved",
        "comments.filter.all": "All",
        "comments.filter.open": "Open",
        "comments.filter.locked": "Locked",
        "comments.filter.answered": "Resolved",
        "comments.time.justNow": "Just now",
        "comments.time.minutesAgo": "{{count}} min ago",
        "comments.time.hoursAgo": "{{count}} hr ago",
        "comments.time.daysAgo": "{{count}} days ago",
        "comments.page.notEnabled": "Comments Plugin Not Enabled",
        "comments.page.notEnabledDesc": "Comment management is provided by the Comments Overview plugin. Please enable it in plugin settings.",
        "comments.page.enablePlugin": "Enable Comments Plugin",
        "comments.page.notConfigured": "Comment System Not Configured",
        "comments.page.notConfiguredDesc": "Please configure Giscus parameters (repository, Repository ID, Category ID) in plugin settings to get started.",
        "comments.page.configureComments": "Configure Comment System",
        "comments.page.title": "Comment Management",
        "comments.page.totalDiscussions": "{{count}} discussions total",
        "comments.page.refresh": "Refresh",
        "comments.page.searchPlaceholder": "Search discussions...",
        "comments.page.loading": "Loading...",
        "comments.page.loadFailed": "Loading failed",
        "comments.page.loadingComments": "Loading comments...",
        "comments.page.noComments": "No comments yet",
        "comments.page.noMatch": "No matching discussions",
        "comments.comment.hidden": "Hidden",
        "comments.comment.unhide": "Unhide",
        "comments.comment.hide": "Hide",
      },
    },
  },
};
